export const BUTTONS=(setExpression, deleteLastValue, solve)=>[
        {
            label:"C",
            action:()=>setExpression(null),
            style:'del'
        },
        {
            label:"<",
            action:()=>deleteLastValue(),
            style:'del'
        },
        {
            label:"%",
            action:()=>setExpression('%'),
            style:'operation'
        },
        {
            label:"/",
            action:()=>setExpression('/'),
            style:'operation'
        },
        {
            label:"7",
            action:()=>setExpression('7')
        },
        {
            label:"8",
            action:()=>setExpression('8')
        },
        {
            label:"9",
            action:()=>setExpression('9')
        },
        {
            label:"*",
            action:()=>setExpression('*'),
            style:'operation'
        },
        {
            label:"4",
            action:()=>setExpression('4')
        },
        {
            label:"5",
            action:()=>setExpression('5')
        },
        {
            label:"6",
            action:()=>setExpression('6')
        },
        {
            label:"-",
            action:()=>setExpression('-'),
            style:'operation'
        },
        {
            label:"1",
            action:()=>setExpression('1')
        },
        {
            label:"2",
            action:()=>setExpression('2')
        },
        {
            label:"3",
            action:()=>setExpression('3')
        },
        {
            label:"+",
            action:()=>setExpression('+'),
            style:'operation'
        },
        {
            label:"0",
            action:()=>setExpression('0')
        },
        {
            label:",",
            action:()=>setExpression(',')
        },
        {
            label:"=",
            action:()=>solve(),
            style:'operation'
        }
    ]