import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    contain:{
        flex:1,
        backgroundColor:'white',
        padding:30
    },
    containerCalculadora:{
        backgroundColor:'#00d564',
        height:500,
        borderRadius:10,
        flexWrap:'wrap'
    },
    boxPantalla:{
        backgroundColor:'#00d564',
        width:'100%',
        padding:20,
        borderRadius:10,
        flex:.5
    },
    pantalla:{
        flex:1,
        backgroundColor:'#ffb200',
        borderRadius:10,
    },
    textResultado:{
        fontSize:22,
        fontWeight:'bold',
        width:'100%',
        padding:10,
        textAlign:'right'
    },
    boxButtons:{
        flex:4,
        display:'flex',
        flexDirection:'row',
        flexWrap:'wrap',
        padding:10,
        backgroundColor:'#ffb200',
        borderRadius:5
    },
    boxButton:{
        width:'25%',
        height:'20%',
        padding:5,
        backgroundColor:'#4bcaf9'
    },
    button:{
        flex:1,
        backgroundColor:'#00d564',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:20
    },
    textButton:{
        fontSize:16,
        fontWeight:'bold'
    },
    red:{
        backgroundColor:'red'
    },
    specialButton:{
        width:'50%'
    },
    specialButtonDel:{
        backgroundColor:'#8a2a2a',
    },
    specialButtonOperations:{
        backgroundColor:'#00b555'
    }
})